services:
  postgres:
    image: postgres:15-alpine
    container_name: fasttodo-postgres
    user: postgres
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=secret
      - POSTGRES_DB=fasttodo
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -d fasttodo -U root"]
      interval: 5s
      timeout: 5s
      retries: 5
  python-app:
    build:
      context: ..
      dockerfile: ./docker/Dockerfile
    ports:
      - "8080:8080"
    environment:
      - POSTGRES_DSN=postgresql://root:secret@fasttodo-postgres:5432/fasttodo?sslmode=disable
      - HOST=0.0.0.0
      - PORT=8080
    depends_on:
      postgres:
        condition: service_healthy
    entrypoint: ["/app/docker/start.sh"]